apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.vault.serviceAccount}}
  namespace: {{.Values.vault.namespace}}
  annotations:
    kubernetes.io/service-account.name: {{.Values.vault.serviceAccount}}
type: kubernetes.io/service-account-token