---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.app.serviceAccount}}
  namespace: {{.Values.app.namespace}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.vault.serviceAccount}}
  namespace: {{.Values.vault.namespace}}