apiVersion: v1
data:
  cluster.name: "{{ .Values.clusterName }}"
  logs.region: "{{ .Values.regionName }}"
  http.server: "{{ .Values.fluentBit.HttpServer }}"
  http.port: "{{ .Values.fluentBit.HttpPort }}"
  read.head: "{{ .Values.fluentBit.ReadHead }}"
  read.tail: "{{ .Values.fluentBit.readTail }}"
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: {{ .Release.Namespace }}