# Default values for argocd-ecr-updater.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

aws:
  accountId: "385284847228"
  region: ap-northeast-3

cronJob:
  name: argocd-ecr-updater-cronjob
  jobName: ecr-cred-helper
  image: odaniait/aws-kubectl:latest
  imagePullPolicy: IfNotPresent
  schedule: "0 0/6 * * *"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  annotations: {}
  name: argocd-ecr-updater

clusterRoleBinding:
  name: argocd-ecr-updater-configure-rbac




